<?php

namespace ContainerMehegqk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EHdw9EYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eHdw9EY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eHdw9EY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projRepository' => ['privates', 'App\\Repository\\ProjRepository', 'getProjRepositoryService', true],
        ], [
            'projRepository' => 'App\\Repository\\ProjRepository',
        ]);
    }
}
