<?php

namespace ContainerXILxh0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CardController' shared autowired service.
     *
     * @return \App\Controller\CardController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CardController'] = $instance = new \App\Controller\CardController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\CardController', $container));

        return $instance;
    }
}
