<?php

namespace ContainerXILxh0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLibraryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LibraryRepository' shared autowired service.
     *
     * @return \App\Repository\LibraryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LibraryRepository'] = new \App\Repository\LibraryRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
