<?php

namespace ContainerR6r4VAv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_63sUQ2WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.63sUQ2W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.63sUQ2W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'plumpRepository' => ['privates', 'App\\Repository\\PlumpRepository', 'getPlumpRepositoryService', true],
        ], [
            'doctrine' => '?',
            'plumpRepository' => 'App\\Repository\\PlumpRepository',
        ]);
    }
}
