<?php

namespace ContainerALkqxjc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XCHIAX6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xCHIAX6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xCHIAX6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\LibraryController::createBookProcess' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\LibraryController::deleteBookByIsbnProcess' => ['privates', '.service_locator.nLzTFMn', 'get_ServiceLocator_NLzTFMnService', true],
            'App\\Controller\\LibraryController::showAllBooks' => ['privates', '.service_locator.TBgEv1t', 'get_ServiceLocator_TBgEv1tService', true],
            'App\\Controller\\LibraryController::showBookByIsbnProcess' => ['privates', '.service_locator.TBgEv1t', 'get_ServiceLocator_TBgEv1tService', true],
            'App\\Controller\\LibraryController::updateBook' => ['privates', '.service_locator.TBgEv1t', 'get_ServiceLocator_TBgEv1tService', true],
            'App\\Controller\\LibraryController::updateBookProcess' => ['privates', '.service_locator.nLzTFMn', 'get_ServiceLocator_NLzTFMnService', true],
            'App\\Controller\\ProjController::endRound' => ['privates', '.service_locator.o6umRUF', 'get_ServiceLocator_O6umRUFService', true],
            'App\\Controller\\ProjController::highscore' => ['privates', '.service_locator.eHdw9EY', 'get_ServiceLocator_EHdw9EYService', true],
            'App\\Controller\\ProjController::layCards' => ['privates', '.service_locator.SnB84of', 'get_ServiceLocator_SnB84ofService', true],
            'App\\Controller\\ProjController::newRound' => ['privates', '.service_locator.8dVHRGV', 'get_ServiceLocator_8dVHRGVService', true],
            'App\\Controller\\ProjController::playGame' => ['privates', '.service_locator.TdK3PfO', 'get_ServiceLocator_TdK3PfOService', true],
            'App\\Controller\\ProjController::plump' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProjController::reset' => ['privates', '.service_locator.ZpXwxdQ', 'get_ServiceLocator_ZpXwxdQService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\LibraryController:createBookProcess' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\LibraryController:deleteBookByIsbnProcess' => ['privates', '.service_locator.nLzTFMn', 'get_ServiceLocator_NLzTFMnService', true],
            'App\\Controller\\LibraryController:showAllBooks' => ['privates', '.service_locator.TBgEv1t', 'get_ServiceLocator_TBgEv1tService', true],
            'App\\Controller\\LibraryController:showBookByIsbnProcess' => ['privates', '.service_locator.TBgEv1t', 'get_ServiceLocator_TBgEv1tService', true],
            'App\\Controller\\LibraryController:updateBook' => ['privates', '.service_locator.TBgEv1t', 'get_ServiceLocator_TBgEv1tService', true],
            'App\\Controller\\LibraryController:updateBookProcess' => ['privates', '.service_locator.nLzTFMn', 'get_ServiceLocator_NLzTFMnService', true],
            'App\\Controller\\ProjController:endRound' => ['privates', '.service_locator.o6umRUF', 'get_ServiceLocator_O6umRUFService', true],
            'App\\Controller\\ProjController:highscore' => ['privates', '.service_locator.eHdw9EY', 'get_ServiceLocator_EHdw9EYService', true],
            'App\\Controller\\ProjController:layCards' => ['privates', '.service_locator.SnB84of', 'get_ServiceLocator_SnB84ofService', true],
            'App\\Controller\\ProjController:newRound' => ['privates', '.service_locator.8dVHRGV', 'get_ServiceLocator_8dVHRGVService', true],
            'App\\Controller\\ProjController:playGame' => ['privates', '.service_locator.TdK3PfO', 'get_ServiceLocator_TdK3PfOService', true],
            'App\\Controller\\ProjController:plump' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProjController:reset' => ['privates', '.service_locator.ZpXwxdQ', 'get_ServiceLocator_ZpXwxdQService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\LibraryController::createBookProcess' => '?',
            'App\\Controller\\LibraryController::deleteBookByIsbnProcess' => '?',
            'App\\Controller\\LibraryController::showAllBooks' => '?',
            'App\\Controller\\LibraryController::showBookByIsbnProcess' => '?',
            'App\\Controller\\LibraryController::updateBook' => '?',
            'App\\Controller\\LibraryController::updateBookProcess' => '?',
            'App\\Controller\\ProjController::endRound' => '?',
            'App\\Controller\\ProjController::highscore' => '?',
            'App\\Controller\\ProjController::layCards' => '?',
            'App\\Controller\\ProjController::newRound' => '?',
            'App\\Controller\\ProjController::playGame' => '?',
            'App\\Controller\\ProjController::plump' => '?',
            'App\\Controller\\ProjController::reset' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\LibraryController:createBookProcess' => '?',
            'App\\Controller\\LibraryController:deleteBookByIsbnProcess' => '?',
            'App\\Controller\\LibraryController:showAllBooks' => '?',
            'App\\Controller\\LibraryController:showBookByIsbnProcess' => '?',
            'App\\Controller\\LibraryController:updateBook' => '?',
            'App\\Controller\\LibraryController:updateBookProcess' => '?',
            'App\\Controller\\ProjController:endRound' => '?',
            'App\\Controller\\ProjController:highscore' => '?',
            'App\\Controller\\ProjController:layCards' => '?',
            'App\\Controller\\ProjController:newRound' => '?',
            'App\\Controller\\ProjController:playGame' => '?',
            'App\\Controller\\ProjController:plump' => '?',
            'App\\Controller\\ProjController:reset' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
