<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxkiSAz\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxkiSAz/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerIxkiSAz.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerIxkiSAz\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerIxkiSAz\App_KernelProdContainer([
    'container.build_hash' => 'IxkiSAz',
    'container.build_id' => 'e89f263b',
    'container.build_time' => 1652185926,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxkiSAz');
