<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXILxh0d\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXILxh0d/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXILxh0d.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXILxh0d\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXILxh0d\App_KernelProdContainer([
    'container.build_hash' => 'XILxh0d',
    'container.build_id' => 'b0088ce7',
    'container.build_time' => 1652188072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXILxh0d');
