<?php

namespace ContainerXdZEtpO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SnB84ofService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SnB84of' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SnB84of'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'game' => ['privates', 'App\\Proj\\Play', NULL, 'Cannot autowire service "App\\Proj\\Play": argument "$players" of method "__construct()" is type-hinted "array", you should configure its value explicitly.'],
            'trumf' => ['privates', 'App\\Proj\\Card', NULL, 'Cannot autowire service "App\\Proj\\Card": argument "$number" of method "__construct()" is type-hinted "int", you should configure its value explicitly.'],
        ], [
            'game' => 'App\\Proj\\Play',
            'trumf' => 'App\\Proj\\Card',
        ]);
    }
}
