<?php

namespace ContainerXdZEtpO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Proj\Card' shared autowired service.
     *
     * @return \App\Proj\Card
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Proj\\Card": argument "$number" of method "__construct()" is type-hinted "int", you should configure its value explicitly.');
    }
}
