<?php

namespace ContainerZy9xhcG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_05Zw2EXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.05Zw2EX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.05Zw2EX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'game' => ['privates', 'App\\Proj\\Play', NULL, 'Cannot autowire service "App\\Proj\\Play": argument "$players" of method "__construct()" is type-hinted "array", you should configure its value explicitly.'],
        ], [
            'doctrine' => '?',
            'game' => 'App\\Proj\\Play',
        ]);
    }
}
