<?php

namespace ContainerZy9xhcG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Proj\Play' shared autowired service.
     *
     * @return \App\Proj\Play
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Proj\\Play": argument "$players" of method "__construct()" is type-hinted "array", you should configure its value explicitly.');
    }
}
