<?php

namespace ContainerJlqVxsw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yb6Jj2dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yb6Jj2d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yb6Jj2d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'check' => ['privates', 'App\\Proj\\Card', NULL, 'Cannot autowire service "App\\Proj\\Card": argument "$number" of method "__construct()" is type-hinted "int", you should configure its value explicitly.'],
        ], [
            'check' => 'App\\Proj\\Card',
        ]);
    }
}
