<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxtQGVZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxtQGVZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFxtQGVZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFxtQGVZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFxtQGVZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'FxtQGVZ',
    'container.build_id' => '9cb91f2b',
    'container.build_time' => 1650451099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxtQGVZ');
