<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGfhehFK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGfhehFK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGfhehFK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGfhehFK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGfhehFK\App_KernelDevDebugContainer([
    'container.build_hash' => 'GfhehFK',
    'container.build_id' => '1b82b1db',
    'container.build_time' => 1654078792,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGfhehFK');
